### ISSUE TITLE
Flashing cursor only, no response from keyboard

### ISSUE THREAD

**Issue by djfergus** [vossstef/tang_nano_9k_6502#6]
Hello. This project seemed to build ok but when I run it I just get a flashing green cursor and nothing else. 

Keyboard, monitor and Tang Nano 9k all work perfectly with your VIC-20 project so doesn't seem like hw issue. 

Not sure if the basic ROM is loading? Not sure where I should start with troubleshooting.

**Comment by vossstef** [comment]
Hi,
pls. do a fresh clone of the repo and program with the Gowin programmer the ready made .fs bitstream (no synthesize)
Green blinking cursor will apear.
Cold[C] or warm [W] start ?
Answer with a 'c' keypress
MEMORY SIZE?
Answer by typing 4096
TERMINAL WIDTH?
Answer by typing 80

System shall response with BASIC xy and OK promt.

If that all works well then you might want to start your own synthesize.
It might be that there a 10K pull up resistors to Tang 5V needed for your keyboard (directly at Keyboard connector side) if you face problems in PS/2.

**Comment by djfergus** [comment]
ok thanks. It works if I program the .fs file from github but fails if I synthesize/pnr myself from source. I'll close this issue and take a look another look at my environment. Curious your other projects build ok except this one. Cheers.
